### ISSUE TITLE
Loading animation not showing correctly 

### ISSUE THREAD

**Issue by tmkasun** [wso2-attic/ux-theme-wso2#41]
Getting loading animation issue When using `data-toggle="loading" data-loading-style="overlay"` without wrapping any content with it, Only show a thin horizontal line. Not showing the loading animation. Please refer the attachment for details.(@thusithak @jeradrutnam )

![theme_issue](https://cloud.githubusercontent.com/assets/3313885/23162657/2c66dc00-f855-11e6-814d-f095c5e1343f.png)

**Comment by thusithak** [comment]
Not a defect. 
Giving a fixed inline-height value just as mentioned  @ http://wso2-dev-ux.github.io/theme-wso2/demo/loading/ would make this right
