### ISSUE TITLE
[extensions] datatable bulk action issue

### ISSUE THREAD

**Issue by dakshika** [wso2-attic/ux-theme-wso2#42]
![dtableissue](https://cloud.githubusercontent.com/assets/6497326/24605513/bcd95fbe-1886-11e7-8e49-2363f21bf2d4.png)

IMO we can improve by providing selection checkbox in-front of each row, then user didn't want to follow specific action before bulk selection. 

But for grid view, we need to come up with similar approach.

**Comment by jeradrutnam** [comment]
Well then we need to find a way to show row expanding icons "+" as well.
